#### Importing important libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from googletrans import Translator

C:\Users\SUSHANT\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

#### importing the dataset

In [2]:
dataFrame = pd.read_csv("dioptra_reviews.csv")

In [3]:
dataFrame.head()

,Unnamed: 0,id,book_title,original_language,edition_language,text,language,author,author_gender,age_category,book_genre,star_rating,tokenised_text,mentions_translation,n_tokens,n_translation_lemmas
0,0,review_1638234481,Nineteen eighty-four,English,English,In a post-Atomic War world three large states ...,English,Joseph Sparrow,male,Adult,Literary fiction,4.0,post atomic war world large state emerge story...,0,174,0
1,1,review_2022355251,Nineteen eighty-four,English,English,"1984 is not a book I would choose myself, beca...",English,Lysanne,female,Adult,Literary fiction,1.0,book choose dystopia theme like kind story lik...,0,18,0
2,2,review_1297147342,Nineteen eighty-four,English,English,"4.5. Woooow, es la primera distopía que se gan...",Spanish,L. C. Julia,unknown,Adult,Literary fiction,4.0,distopía ganar estrellar y jajaja humor ironic...,0,17,0
3,3,review_2067357280,Nineteen eighty-four,English,English,Relevant reading for today To understand the f...,English,Lori Ghany,female,Adult,Literary fiction,5.0,relevant reading understand future look past u...,0,21,0
4,4,review_3122615894,Nineteen eighty-four,English,English,This is one of those books you should not read...,English,Balthazar Hawke,unknown,Adult,Literary fiction,5.0,book read ready read sure piece fall right bel...,0,26,0

In [4]:
dataFrame.tail()

,Unnamed: 0,id,book_title,original_language,edition_language,text,language,author,author_gender,age_category,book_genre,star_rating,tokenised_text,mentions_translation,n_tokens,n_translation_lemmas
270395,294159,review_3274625836,Le petit prince,French,Spanish,"No creo que este libro sea para niÃ±os, mÃ¡s b...",Spanish,Claudia_milpalabras,unknown,Children,Literary fiction,4.0,librar personar llevar,0,3,0
270396,294160,review_2651143337,Le petit prince,French,Spanish,"Difícil de creer o no, fue la primera vez que ...",Spanish,Oliv (bookishbruha),unknown,Children,Literary fiction,5.0,difícil creer o leer y entender lectura sensac...,0,67,0
270397,294161,review_943473274,Le petit prince,French,Italian,"Come un libro così piccolo, possa esprimere co...",Italian,Veronica,female,Children,Literary fiction,5.0,librare piccolo esprimere cosa grande letto e ...,0,18,0
270398,294162,review_2914260592,Le petit prince,French,English,"Safe to say, this grown-up has been tamed by t...",English,Bibliophile Doctor,unknown,Children,Literary fiction,5.0,safe grow tame book funny little book land pla...,0,231,0
270399,294163,review_157432613,Le petit prince,French,English,Il n'y eut rien qu'un êclair jaune près de sa ...,French,Ali,male,Children,Literary fiction,5.0,y avoir êclair jaune cheville demeurer instant...,0,21,0

## Data Cleaning

In [5]:
dataFrame.dtypes

Unnamed: 0                int64
id                       object
book_title               object
original_language        object
edition_language         object
text                     object
language                 object
author                   object
author_gender            object
age_category             object
book_genre               object
star_rating             float64
tokenised_text           object
mentions_translation      int64
n_tokens                  int64
n_translation_lemmas      int64
dtype: object

In [6]:
dataFrame.shape

(270400, 16)

In [7]:
dataFrame.apply(lambda x: x.count())

Unnamed: 0              270400
id                      270400
book_title              270400
original_language       270400
edition_language        270400
text                    270400
language                270400
author                  270400
author_gender           270400
age_category            270400
book_genre              270400
star_rating             266437
tokenised_text          270400
mentions_translation    270400
n_tokens                270400
n_translation_lemmas    270400
dtype: int64

In [8]:
dataFrame[dataFrame.isnull().any(axis=1)].count()

Unnamed: 0              3963
id                      3963
book_title              3963
original_language       3963
edition_language        3963
text                    3963
language                3963
author                  3963
author_gender           3963
age_category            3963
book_genre              3963
star_rating                0
tokenised_text          3963
mentions_translation    3963
n_tokens                3963
n_translation_lemmas    3963
dtype: int64

#### dropping null values

In [9]:
dataFrame = dataFrame.dropna()

In [10]:
dataFrame['language'].value_counts()

English       200473
Spanish        30918
Italian        11492
Portuguese      6853
French          6565
Dutch           5356
German          4780
Name: language, dtype: int64

#### dropping rows with reviews in languages other than english

In [11]:
dataFrame = dataFrame[dataFrame['language'] == 'English']

In [12]:
dataFrame['language'].value_counts()

English    200473
Name: language, dtype: int64

In [13]:
dataFrame.head()

,Unnamed: 0,id,book_title,original_language,edition_language,text,language,author,author_gender,age_category,book_genre,star_rating,tokenised_text,mentions_translation,n_tokens,n_translation_lemmas
0,0,review_1638234481,Nineteen eighty-four,English,English,In a post-Atomic War world three large states ...,English,Joseph Sparrow,male,Adult,Literary fiction,4.0,post atomic war world large state emerge story...,0,174,0
1,1,review_2022355251,Nineteen eighty-four,English,English,"1984 is not a book I would choose myself, beca...",English,Lysanne,female,Adult,Literary fiction,1.0,book choose dystopia theme like kind story lik...,0,18,0
3,3,review_2067357280,Nineteen eighty-four,English,English,Relevant reading for today To understand the f...,English,Lori Ghany,female,Adult,Literary fiction,5.0,relevant reading understand future look past u...,0,21,0
4,4,review_3122615894,Nineteen eighty-four,English,English,This is one of those books you should not read...,English,Balthazar Hawke,unknown,Adult,Literary fiction,5.0,book read ready read sure piece fall right bel...,0,26,0
6,6,review_135690649,Nineteen eighty-four,English,English,It is tempting with the `wisdom' of the twenti...,English,Jordan Forster,male,Adult,Literary fiction,3.0,tempt wisdom dismiss irrelevant book guilty fa...,0,408,0

In [14]:
dataFrame['author_gender'].value_counts()

female           98190
unknown          42691
male             41677
mostly_female    10273
mostly_male       5247
andy              2395
Name: author_gender, dtype: int64

#### converting genders mostly_male and mostly_female to male and female respectively

In [15]:
dataFrame['author_gender'] = dataFrame['author_gender'].replace({'mostly_male': 'male', 'mostly_female': 'female'})

In [16]:
dataFrame['author_gender'].value_counts()

female     108463
male        46924
unknown     42691
andy         2395
Name: author_gender, dtype: int64

In [17]:
dataFrame = dataFrame.drop(dataFrame[dataFrame['author_gender'] == 'andy'].index)

In [18]:
dataFrame['author_gender'].value_counts()

female     108463
male        46924
unknown     42691
Name: author_gender, dtype: int64

In [19]:
dataFrame['age_category'].value_counts()

Adult          137057
Children        39736
Young adult     21285
Name: age_category, dtype: int64

In [20]:
dataFrame.head()

,Unnamed: 0,id,book_title,original_language,edition_language,text,language,author,author_gender,age_category,book_genre,star_rating,tokenised_text,mentions_translation,n_tokens,n_translation_lemmas
0,0,review_1638234481,Nineteen eighty-four,English,English,In a post-Atomic War world three large states ...,English,Joseph Sparrow,male,Adult,Literary fiction,4.0,post atomic war world large state emerge story...,0,174,0
1,1,review_2022355251,Nineteen eighty-four,English,English,"1984 is not a book I would choose myself, beca...",English,Lysanne,female,Adult,Literary fiction,1.0,book choose dystopia theme like kind story lik...,0,18,0
3,3,review_2067357280,Nineteen eighty-four,English,English,Relevant reading for today To understand the f...,English,Lori Ghany,female,Adult,Literary fiction,5.0,relevant reading understand future look past u...,0,21,0
4,4,review_3122615894,Nineteen eighty-four,English,English,This is one of those books you should not read...,English,Balthazar Hawke,unknown,Adult,Literary fiction,5.0,book read ready read sure piece fall right bel...,0,26,0
6,6,review_135690649,Nineteen eighty-four,English,English,It is tempting with the `wisdom' of the twenti...,English,Jordan Forster,male,Adult,Literary fiction,3.0,tempt wisdom dismiss irrelevant book guilty fa...,0,408,0

In [21]:
print(dataFrame['text'][0])
dataFrame['tokenised_text'][0]

In a post-Atomic War world three large states emerge: Oceania, Eastasia and Eurasia. Our story takes place in London which is ruled by Oceania. The Government is known as The Party which has complete and utter control over it's citizens. Enter Winston Smith who is a medium class citizen and works with the Party. His resentment towards the Party continually grows as he commits crimes such as having an affair and actively avoiding the Party's security devices. However in the end, no one can truly escape the Party's grasp. The Story takes place in a dystopic London where the citizens are under constant threat of being bombed by enemy nations. The Party enlists the Ministry of Truth which throws out constant displays of propaganda with the use of Telescreens. However the same Telescreens are also used by the Ministry Of Love to monitor the populous, they oversee every conversation and action, constantly looking for someone who could be against the Party. The Thought Police are also used to detect anyone who could be against the Party. Our Protagonist Winston Smith works in the Ministry of Truth where he forges historic documents that favors the Party's current needs. As the years go on Winston begins to notice the Party's true, evil intentions and begins to commit small crimes in resentment. Soon he begins to fall in love and have a affair with a girl named Julia who shares his hate for the Party. Eventually he becomes friends with a suspicious Inner Party Member, named O'Brien who shows Winston almost everything about the Party, their intentions and the worlds true history. I found '1984' to be a extremely suspenseful novel. The characters are constantly doing things that disobey the Party and it's laws, you never know when they might get caught. The characters know that it isn't 'if' it's 'when' they will get caught and when they eventually do it's a great plot twist. However not everything in 1984 is attention grabbing. I think that the "Goldsteins Book" section could have been done much better. Goldsteins Book broke the suspense, is overly complicated and overall I found it hard to follow. It was over 30 pages of a boring mess and I was glad when finally Winston put Goldsteins Book down. Goldsteins Book presented a harrowing dystopic world and I felt that the backstory had a lot of potential. This potential lost ground as I found that the worlds and the Party's lore dropped my interest. I believe a audience that would like this book would be people who like sci-fi and those who are into conspiracy theories. In the end I enjoyed 1984. It has a suspenseful and very interesting storyline. Some parts of the novel could have definitely been improved on, however in the end I would recommend it as a classic novel worthy of time and attention.

'post atomic war world large state emerge story take place rule government know complete utter control citizen enter medium class citizen work resentment continually grow commit crime have affair actively avoid security device end truly escape grasp story take place dystopic citizen constant threat bomb enemy nation enlist throw constant display propaganda use monitor populous oversee conversation action constantly look detect protagonist work forge historic document favor current need begin notice true evil intention begin commit small crime resentment soon begin fall love affair girl name share hate eventually friend suspicious member name show intention world true history find extremely suspenseful novel character constantly thing disobey law know catch character know catch eventually great plot twist attention grab think section well break suspense overly complicated overall find hard follow page boring mess glad finally present harrowing dystopic world feel backstory lot potential potential lose ground find world lore drop interest believe audience like book people like conspiracy theory end enjoy suspenseful interesting storyline part novel definitely improve end recommend classic novel worthy time attention'

In [22]:
dataFrame['text'] = dataFrame['text'].str.replace('[^a-zA-Z\s]', '')
dataFrame['tokenised_text'] = dataFrame['tokenised_text'].str.replace('[^a-zA-Z\s]', '')

C:\Users\SUSHANT\AppData\Local\Temp\ipykernel_7784\667326341.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  dataFrame['text'] = dataFrame['text'].str.replace('[^a-zA-Z\s]', '')
C:\Users\SUSHANT\AppData\Local\Temp\ipykernel_7784\667326341.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  dataFrame['tokenised_text'] = dataFrame['tokenised_text'].str.replace('[^a-zA-Z\s]', '')

#### importing BertTokenizer for tokenising to textual reviews

In [23]:
from transformers import BertTokenizer

In [24]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [25]:
dataFrame['bert_tokenized_text'] = dataFrame['text'].apply(lambda x: tokenizer.tokenize(x))

In [26]:
dataFrame.head()

,Unnamed: 0,id,book_title,original_language,edition_language,text,language,author,author_gender,age_category,book_genre,star_rating,tokenised_text,mentions_translation,n_tokens,n_translation_lemmas,bert_tokenized_text
0,0,review_1638234481,Nineteen eighty-four,English,English,In a postAtomic War world three large states e...,English,Joseph Sparrow,male,Adult,Literary fiction,4.0,post atomic war world large state emerge story...,0,174,0,"[in, a, post, ##ato, ##mic, war, world, three,..."
1,1,review_2022355251,Nineteen eighty-four,English,English,is not a book I would choose myself because o...,English,Lysanne,female,Adult,Literary fiction,1.0,book choose dystopia theme like kind story lik...,0,18,0,"[is, not, a, book, i, would, choose, myself, b..."
3,3,review_2067357280,Nineteen eighty-four,English,English,Relevant reading for today To understand the f...,English,Lori Ghany,female,Adult,Literary fiction,5.0,relevant reading understand future look past u...,0,21,0,"[relevant, reading, for, today, to, understand..."
4,4,review_3122615894,Nineteen eighty-four,English,English,This is one of those books you should not read...,English,Balthazar Hawke,unknown,Adult,Literary fiction,5.0,book read ready read sure piece fall right bel...,0,26,0,"[this, is, one, of, those, books, you, should,..."
6,6,review_135690649,Nineteen eighty-four,English,English,It is tempting with the wisdom of the twentiet...,English,Jordan Forster,male,Adult,Literary fiction,3.0,tempt wisdom dismiss irrelevant book guilty fa...,0,408,0,"[it, is, tempting, with, the, wisdom, of, the,..."

In [27]:
(dataFrame['text'][0])

'In a postAtomic War world three large states emerge Oceania Eastasia and Eurasia Our story takes place in London which is ruled by Oceania The Government is known as The Party which has complete and utter control over its citizens Enter Winston Smith who is a medium class citizen and works with the Party His resentment towards the Party continually grows as he commits crimes such as having an affair and actively avoiding the Partys security devices However in the end no one can truly escape the Partys grasp The Story takes place in a dystopic London where the citizens are under constant threat of being bombed by enemy nations The Party enlists the Ministry of Truth which throws out constant displays of propaganda with the use of Telescreens However the same Telescreens are also used by the Ministry Of Love to monitor the populous they oversee every conversation and action constantly looking for someone who could be against the Party The Thought Police are also used to detect anyone who could be against the Party Our Protagonist Winston Smith works in the Ministry of Truth where he forges historic documents that favors the Partys current needs As the years go on Winston begins to notice the Partys true evil intentions and begins to commit small crimes in resentment Soon he begins to fall in love and have a affair with a girl named Julia who shares his hate for the Party Eventually he becomes friends with a suspicious Inner Party Member named OBrien who shows Winston almost everything about the Party their intentions and the worlds true history I found  to be a extremely suspenseful novel The characters are constantly doing things that disobey the Party and its laws you never know when they might get caught The characters know that it isnt if its when they will get caught and when they eventually do its a great plot twist However not everything in  is attention grabbing I think that the Goldsteins Book section could have been done much better Goldsteins Book broke the suspense is overly complicated and overall I found it hard to follow It was over  pages of a boring mess and I was glad when finally Winston put Goldsteins Book down Goldsteins Book presented a harrowing dystopic world and I felt that the backstory had a lot of potential This potential lost ground as I found that the worlds and the Partys lore dropped my interest I believe a audience that would like this book would be people who like scifi and those who are into conspiracy theories In the end I enjoyed  It has a suspenseful and very interesting storyline Some parts of the novel could have definitely been improved on however in the end I would recommend it as a classic novel worthy of time and attention'

In [28]:
dataFrame['bert_tokenized_text'][0]

['in',
 'a',
 'post',
 '##ato',
 '##mic',
 'war',
 'world',
 'three',
 'large',
 'states',
 'emerge',
 'oceania',
 'east',
 '##asia',
 'and',
 'eu',
 '##rasia',
 'our',
 'story',
 'takes',
 'place',
 'in',
 'london',
 'which',
 'is',
 'ruled',
 'by',
 'oceania',
 'the',
 'government',
 'is',
 'known',
 'as',
 'the',
 'party',
 'which',
 'has',
 'complete',
 'and',
 'utter',
 'control',
 'over',
 'its',
 'citizens',
 'enter',
 'winston',
 'smith',
 'who',
 'is',
 'a',
 'medium',
 'class',
 'citizen',
 'and',
 'works',
 'with',
 'the',
 'party',
 'his',
 'resentment',
 'towards',
 'the',
 'party',
 'continually',
 'grows',
 'as',
 'he',
 'commits',
 'crimes',
 'such',
 'as',
 'having',
 'an',
 'affair',
 'and',
 'actively',
 'avoiding',
 'the',
 'party',
 '##s',
 'security',
 'devices',
 'however',
 'in',
 'the',
 'end',
 'no',
 'one',
 'can',
 'truly',
 'escape',
 'the',
 'party',
 '##s',
 'grasp',
 'the',
 'story',
 'takes',
 'place',
 'in',
 'a',
 'd',
 '##yst',
 '##op',
 '##ic',
 'london',
 'where',
 'the',
 'citizens',
 'are',
 'under',
 'constant',
 'threat',
 'of',
 'being',
 'bombed',
 'by',
 'enemy',
 'nations',
 'the',
 'party',
 'enlist',
 '##s',
 'the',
 'ministry',
 'of',
 'truth',
 'which',
 'throws',
 'out',
 'constant',
 'displays',
 'of',
 'propaganda',
 'with',
 'the',
 'use',
 'of',
 'tel',
 '##es',
 '##creen',
 '##s',
 'however',
 'the',
 'same',
 'tel',
 '##es',
 '##creen',
 '##s',
 'are',
 'also',
 'used',
 'by',
 'the',
 'ministry',
 'of',
 'love',
 'to',
 'monitor',
 'the',
 'populous',
 'they',
 'oversee',
 'every',
 'conversation',
 'and',
 'action',
 'constantly',
 'looking',
 'for',
 'someone',
 'who',
 'could',
 'be',
 'against',
 'the',
 'party',
 'the',
 'thought',
 'police',
 'are',
 'also',
 'used',
 'to',
 'detect',
 'anyone',
 'who',
 'could',
 'be',
 'against',
 'the',
 'party',
 'our',
 'protagonist',
 'winston',
 'smith',
 'works',
 'in',
 'the',
 'ministry',
 'of',
 'truth',
 'where',
 'he',
 'forge',
 '##s',
 'historic',
 'documents',
 'that',
 'favors',
 'the',
 'party',
 '##s',
 'current',
 'needs',
 'as',
 'the',
 'years',
 'go',
 'on',
 'winston',
 'begins',
 'to',
 'notice',
 'the',
 'party',
 '##s',
 'true',
 'evil',
 'intentions',
 'and',
 'begins',
 'to',
 'commit',
 'small',
 'crimes',
 'in',
 'resentment',
 'soon',
 'he',
 'begins',
 'to',
 'fall',
 'in',
 'love',
 'and',
 'have',
 'a',
 'affair',
 'with',
 'a',
 'girl',
 'named',
 'julia',
 'who',
 'shares',
 'his',
 'hate',
 'for',
 'the',
 'party',
 'eventually',
 'he',
 'becomes',
 'friends',
 'with',
 'a',
 'suspicious',
 'inner',
 'party',
 'member',
 'named',
 'ob',
 '##rien',
 'who',
 'shows',
 'winston',
 'almost',
 'everything',
 'about',
 'the',
 'party',
 'their',
 'intentions',
 'and',
 'the',
 'worlds',
 'true',
 'history',
 'i',
 'found',
 'to',
 'be',
 'a',
 'extremely',
 'suspense',
 '##ful',
 'novel',
 'the',
 'characters',
 'are',
 'constantly',
 'doing',
 'things',
 'that',
 'di',
 '##so',
 '##bey',
 'the',
 'party',
 'and',
 'its',
 'laws',
 'you',
 'never',
 'know',
 'when',
 'they',
 'might',
 'get',
 'caught',
 'the',
 'characters',
 'know',
 'that',
 'it',
 'isn',
 '##t',
 'if',
 'its',
 'when',
 'they',
 'will',
 'get',
 'caught',
 'and',
 'when',
 'they',
 'eventually',
 'do',
 'its',
 'a',
 'great',
 'plot',
 'twist',
 'however',
 'not',
 'everything',
 'in',
 'is',
 'attention',
 'grabbing',
 'i',
 'think',
 'that',
 'the',
 'goldstein',
 '##s',
 'book',
 'section',
 'could',
 'have',
 'been',
 'done',
 'much',
 'better',
 'goldstein',
 '##s',
 'book',
 'broke',
 'the',
 'suspense',
 'is',
 'overly',
 'complicated',
 'and',
 'overall',
 'i',
 'found',
 'it',
 'hard',
 'to',
 'follow',
 'it',
 'was',
 'over',
 'pages',
 'of',
 'a',
 'boring',
 'mess',
 'and',
 'i',
 'was',
 'glad',
 'when',
 'finally',
 'winston',
 'put',
 'goldstein',
 '##s',
 'book',
 'down',
 'goldstein',
 '##s',
 'book',
 'presented',
 'a',
 'harrow',
 '##ing',
 'd',
 '##yst',
 '##op',
 '##ic',
 'world',
 'and',
 'i',
 'felt',
 'that',
 'the',
 'backs',
 '##tory',
 'had',
 'a',
 'lot',
 'of',
 'potential',
 'this',
 'potential',
 'lost',
 'ground',
 'as',
 'i',
 'found',
 'that',
 'the',
 'worlds',
 'and',
 'the',
 'party',
 '##s',
 'lore',
 'dropped',
 'my',
 'interest',
 'i',
 'believe',
 'a',
 'audience',
 'that',
 'would',
 'like',
 'this',
 'book',
 'would',
 'be',
 'people',
 'who',
 'like',
 'sci',
 '##fi',
 'and',
 'those',
 'who',
 'are',
 'into',
 'conspiracy',
 'theories',
 'in',
 'the',
 'end',
 'i',
 'enjoyed',
 'it',
 'has',
 'a',
 'suspense',
 '##ful',
 'and',
 'very',
 'interesting',
 'storyline',
 'some',
 'parts',
 'of',
 'the',
 'novel',
 'could',
 'have',
 'definitely',
 'been',
 'improved',
 'on',
 'however',
 'in',
 'the',
 'end',
 'i',
 'would',
 'recommend',
 'it',
 'as',
 'a',
 'classic',
 'novel',
 'worthy',
 'of',
 'time',
 'and',
 'attention']

In [29]:
from keras.preprocessing.sequence import pad_sequences

WARNING:tensorflow:From C:\Users\SUSHANT\anaconda3\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [30]:
# Converting tokenized text to token IDs
dataFrame['bert_tokenized_text_ids'] = dataFrame['bert_tokenized_text'].apply(lambda x: tokenizer.convert_tokens_to_ids(x))

In [31]:
# Padding the tokenized sequences to a length of 512 which is suitable for BERT input
max_length = 512
padded_sequences = pad_sequences(dataFrame['bert_tokenized_text_ids'], maxlen=max_length, padding='post', truncating='post')
dataFrame['padded_sequences'] = list(padded_sequences)

In [32]:
dataFrame.head()

,Unnamed: 0,id,book_title,original_language,edition_language,text,language,author,author_gender,age_category,book_genre,star_rating,tokenised_text,mentions_translation,n_tokens,n_translation_lemmas,bert_tokenized_text,bert_tokenized_text_ids,padded_sequences
0,0,review_1638234481,Nineteen eighty-four,English,English,In a postAtomic War world three large states e...,English,Joseph Sparrow,male,Adult,Literary fiction,4.0,post atomic war world large state emerge story...,0,174,0,"[in, a, post, ##ato, ##mic, war, world, three,...","[1999, 1037, 2695, 10610, 7712, 2162, 2088, 20...","[1999, 1037, 2695, 10610, 7712, 2162, 2088, 20..."
1,1,review_2022355251,Nineteen eighty-four,English,English,is not a book I would choose myself because o...,English,Lysanne,female,Adult,Literary fiction,1.0,book choose dystopia theme like kind story lik...,0,18,0,"[is, not, a, book, i, would, choose, myself, b...","[2003, 2025, 1037, 2338, 1045, 2052, 5454, 287...","[2003, 2025, 1037, 2338, 1045, 2052, 5454, 287..."
3,3,review_2067357280,Nineteen eighty-four,English,English,Relevant reading for today To understand the f...,English,Lori Ghany,female,Adult,Literary fiction,5.0,relevant reading understand future look past u...,0,21,0,"[relevant, reading, for, today, to, understand...","[7882, 3752, 2005, 2651, 2000, 3305, 1996, 292...","[7882, 3752, 2005, 2651, 2000, 3305, 1996, 292..."
4,4,review_3122615894,Nineteen eighty-four,English,English,This is one of those books you should not read...,English,Balthazar Hawke,unknown,Adult,Literary fiction,5.0,book read ready read sure piece fall right bel...,0,26,0,"[this, is, one, of, those, books, you, should,...","[2023, 2003, 2028, 1997, 2216, 2808, 2017, 232...","[2023, 2003, 2028, 1997, 2216, 2808, 2017, 232..."
6,6,review_135690649,Nineteen eighty-four,English,English,It is tempting with the wisdom of the twentiet...,English,Jordan Forster,male,Adult,Literary fiction,3.0,tempt wisdom dismiss irrelevant book guilty fa...,0,408,0,"[it, is, tempting, with, the, wisdom, of, the,...","[2009, 2003, 23421, 2007, 1996, 9866, 1997, 19...","[2009, 2003, 23421, 2007, 1996, 9866, 1997, 19..."

In [33]:
# Adding special tokens [CLS] and [SEP]
padded_sequences_with_special_tokens = []
for seq in dataFrame['padded_sequences']:
    padded_sequences_with_special_tokens.append([tokenizer.cls_token_id] + seq + [tokenizer.sep_token_id])

In [34]:
# Creating segment IDs (all zeros for single-sequence classification)
segment_ids = [[0] * max_length for _ in range(len(dataFrame))]

In [35]:
# Creating attention masks (1 for real tokens, 0 for padding tokens)
attention_masks = []
for seq in padded_sequences_with_special_tokens:
    mask = [1] * len(seq) + [0] * (max_length - len(seq))
    attention_masks.append(mask)

In [40]:
# Updating the DataFrame with the formatted sequences
dataFrame['input_ids'] = padded_sequences_with_special_tokens
dataFrame['segment_ids'] = segment_ids
dataFrame['attention_masks'] = attention_masks

In [41]:
dataFrame.head()

,Unnamed: 0,id,book_title,original_language,edition_language,text,language,author,author_gender,age_category,...,tokenised_text,mentions_translation,n_tokens,n_translation_lemmas,bert_tokenized_text,bert_tokenized_text_ids,padded_sequences,input_ids,segment_ids,attention_masks
0,0,review_1638234481,Nineteen eighty-four,English,English,In a postAtomic War world three large states e...,English,Joseph Sparrow,male,Adult,...,post atomic war world large state emerge story...,0,174,0,"[in, a, post, ##ato, ##mic, war, world, three,...","[1999, 1037, 2695, 10610, 7712, 2162, 2088, 20...","[1999, 1037, 2695, 10610, 7712, 2162, 2088, 20...","[2202, 1240, 2898, 10813, 7915, 2365, 2291, 22...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,1,review_2022355251,Nineteen eighty-four,English,English,is not a book I would choose myself because o...,English,Lysanne,female,Adult,...,book choose dystopia theme like kind story lik...,0,18,0,"[is, not, a, book, i, would, choose, myself, b...","[2003, 2025, 1037, 2338, 1045, 2052, 5454, 287...","[2003, 2025, 1037, 2338, 1045, 2052, 5454, 287...","[2206, 2228, 1240, 2541, 1248, 2255, 5657, 307...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,3,review_2067357280,Nineteen eighty-four,English,English,Relevant reading for today To understand the f...,English,Lori Ghany,female,Adult,...,relevant reading understand future look past u...,0,21,0,"[relevant, reading, for, today, to, understand...","[7882, 3752, 2005, 2651, 2000, 3305, 1996, 292...","[7882, 3752, 2005, 2651, 2000, 3305, 1996, 292...","[8085, 3955, 2208, 2854, 2203, 3508, 2199, 312...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,4,review_3122615894,Nineteen eighty-four,English,English,This is one of those books you should not read...,English,Balthazar Hawke,unknown,Adult,...,book read ready read sure piece fall right bel...,0,26,0,"[this, is, one, of, those, books, you, should,...","[2023, 2003, 2028, 1997, 2216, 2808, 2017, 232...","[2023, 2003, 2028, 1997, 2216, 2808, 2017, 232...","[2226, 2206, 2231, 2200, 2419, 3011, 2220, 252...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
6,6,review_135690649,Nineteen eighty-four,English,English,It is tempting with the wisdom of the twentiet...,English,Jordan Forster,male,Adult,...,tempt wisdom dismiss irrelevant book guilty fa...,0,408,0,"[it, is, tempting, with, the, wisdom, of, the,...","[2009, 2003, 23421, 2007, 1996, 9866, 1997, 19...","[2009, 2003, 23421, 2007, 1996, 9866, 1997, 19...","[2212, 2206, 23624, 2210, 2199, 10069, 2200, 2...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [42]:
from transformers import BertModel, BertTokenizer
import torch

In [43]:
from transformers import TFBertModel, BertTokenizer
model = TFBertModel.from_pretrained('bert-base-uncased')

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

In [44]:
# Converting input data to TensorFlow tensors
import tensorflow as tf
input_ids_tf = tf.convert_to_tensor(dataFrame['input_ids'].tolist())
attention_masks_tf = tf.convert_to_tensor(dataFrame['attention_masks'].tolist())
segment_ids_tf = tf.convert_to_tensor(dataFrame['segment_ids'].tolist())

In [58]:
import numpy as np

batch_size = 32  # Choose an appropriate batch size

# Obtain contextual embeddings in batches
num_batches = 4 #len(input_ids_tf) // batch_size
all_sentiment_scores = []
np.set_printoptions(precision=4, suppress=True)

for i in range(num_batches):
    # Calculate the start and end index for the current batch
    start_idx = i * batch_size
    end_idx = min((i + 1) * batch_size, len(dataFrame))

    # Get a batch of input data
    input_ids_batch = input_ids_tf[start_idx:end_idx]
    attention_masks_batch = attention_masks_tf[start_idx:end_idx]
    segment_ids_batch = segment_ids_tf[start_idx:end_idx]

    # Obtain contextual embeddings
    with tf.device('/cpu:0'):  # Use CPU for tokenization
        outputs = model(input_ids_batch, attention_mask=attention_masks_batch, token_type_ids=segment_ids_batch)

    # Get the contextual embeddings for the first token ([CLS] token)
    embedding = outputs.last_hidden_state[:, 0, :]

    # Add a classification head (linear layer without activation) to predict sentiment scores
#     classification_head = tf.keras.layers.Dense(1)
    classification_head = tf.keras.layers.Dense(1, activation='tanh')
    sentiment_scores = classification_head(embedding)

    # Scale the sentiment scores to the range [-1, 1]
    sentiment_scores_scaled = 2 * tf.keras.activations.tanh(sentiment_scores)

    # Append the sentiment scores to the list
    all_sentiment_scores.append(sentiment_scores_scaled.numpy())

# Convert the list of sentiment scores to a numpy array
all_sentiment_scores = np.concatenate(all_sentiment_scores, axis=0)

# Print the scaled sentiment scores for the entire dataset
print((all_sentiment_scores))

[[-0.1574]
 [-0.8472]
 [-1.0502]
 [-0.9775]
 [ 0.1471]
 [-0.6478]
 [-0.6948]
 [-0.2261]
 [-1.118 ]
 [-0.6461]
 [-0.2552]
 [-0.9589]
 [ 0.8012]
 [-0.7837]
 [-1.0547]
 [-0.2183]
 [-0.5774]
 [-1.1254]
 [-0.1304]
 [-1.0973]
 [ 0.0623]
 [-1.2794]
 [-0.1363]
 [-1.1531]
 [ 0.0632]
 [-0.6518]
 [-0.985 ]
 [ 0.0305]
 [-0.5738]
 [-0.6031]
 [-0.9005]
 [-0.2491]
 [ 1.1863]
 [-1.1592]
 [-0.3598]
 [-1.0186]
 [ 0.6192]
 [ 1.2426]
 [-0.6665]
 [ 1.1973]
 [ 0.8526]
 [ 0.642 ]
 [ 0.9964]
 [ 0.604 ]
 [-0.9117]
 [ 0.6952]
 [-0.1645]
 [ 0.918 ]
 [ 1.1682]
 [ 1.0983]
 [-0.4193]
 [ 0.5217]
 [ 0.3279]
 [ 0.8474]
 [ 0.1986]
 [ 0.2315]
 [ 0.5591]
 [ 0.8087]
 [ 0.9701]
 [-0.8845]
 [-0.7581]
 [ 1.1931]
 [ 0.4443]
 [-0.4322]
 [-1.1398]
 [-1.4525]
 [-1.327 ]
 [-0.0363]
 [ 1.0224]
 [ 0.0171]
 [-0.0525]
 [-1.0829]
 [-0.3129]
 [-0.6436]
 [-1.3783]
 [-1.4546]
 [-1.0533]
 [ 0.5359]
 [-1.4852]
 [-1.4004]
 [ 0.4506]
 [-1.2664]
 [-0.2544]
 [-1.3718]
 [ 0.299 ]
 [-0.2475]
 [ 0.18  ]
 [-1.1573]
 [-0.0345]
 [-0.4651]
 [-0.262 ]
 [-1.1965]
 [-1.4298]
 [-1.2696]
 [ 0.263 ]
 [-1.3359]
 [ 0.8662]
 [ 0.4371]
 [ 0.6615]
 [ 0.3545]
 [ 1.1854]
 [ 0.9138]
 [ 1.0732]
 [ 1.3337]
 [ 1.1548]
 [ 1.0327]
 [ 0.1715]
 [ 0.8717]
 [ 0.3929]
 [ 0.7895]
 [ 0.976 ]
 [ 0.9761]
 [ 1.1637]
 [ 0.7788]
 [ 1.3314]
 [ 0.6799]
 [ 1.0195]
 [ 0.6687]
 [ 0.8267]
 [ 0.9991]
 [ 0.3579]
 [-0.3969]
 [ 0.8444]
 [ 0.3629]
 [ 1.0966]
 [ 0.9411]
 [ 0.9386]
 [ 0.6641]]

In [56]:
print(len(all_sentiment_scores))

128